DATA:
  ROOT: ./datasets
  DATASET: cifar10
  HEIGHT: 224
  WIDTH: 224
  TRAIN_BATCH: 128
  TEST_BATCH: 256
  NUM_WORKERS: 8
MODEL:
  NAME: vit_base
  SHADOW_NAME: vit_base
  STUDENT_NAME: deit_base
  CLASS_NUM: 10
TRAIN:
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 20
  TARGET: 1
  KD_WEIGHT: 0.5
  MASK_WEIGHT: 0.01
  META_WEIGHT: 0.5
  INNER_LR: 0.0005
  TRIGGER_LR_MULTIPLIER: 5.0
  SHADOW_LR_MULTIPLIER: 1.0
  OPTIMIZER:
    NAME: adamw
    LR: 0.0005
    WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    STEPSIZE: [100, 150]
    DECAY_RATE: 0.1
TEST:
  START_EVAL: 0
  EVAL_STEP: 10
SEED: 1024
OUTPUT: ./outputs
TAG: vit_base
