DATA:
  ROOT: ./datasets/imagenet-1k
  DATASET: imagenet
  HEIGHT: 224
  WIDTH: 224
  TRAIN_BATCH: 64
  TEST_BATCH: 256
  NUM_WORKERS: 8
MODEL:
  NAME: resnet50
  SHADOW_NAME: resnet50
  STUDENT_NAME: resnet34
  CLASS_NUM: 1000
TRAIN:
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 20
  TARGET: 1
  KD_WEIGHT: 0.5
  MASK_WEIGHT: 0.01
  META_WEIGHT: 0.5
  INNER_LR: 0.0005
  OPTIMIZER:
    NAME: sgd
    LR: 0.1
    WEIGHT_DECAY: 0.0005
  LR_SCHEDULER:
    STEPSIZE: [100, 150]
    DECAY_RATE: 0.1
TEST:
  START_EVAL: 0
  EVAL_STEP: 10
SEED: 1024
OUTPUT: ./outputs
TAG: resnet50
